tracker_homepage:
    pattern:  /tracking/
    defaults: { _controller: TrackerBundle:Default:index }

tracker_user:
    resource: "@TrackerBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /tracking/user

tracker_project:
    resource: "@TrackerBundle/Controller/ProjectController.php"
    type:     annotation
    prefix:   /tracking/project

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /