services:
    tracker_user.registration.type:
        class: Oro\TrackerBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: tracker_user_registration }

    event.listener:
        class: Oro\TrackerBundle\EventListener\EntityListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    issue:
        class: Oro\TrackerBundle\Service\Issue
        arguments: ['@service_container']

    activity:
        class: Oro\TrackerBundle\Service\Activity
        arguments: ['@service_container']