services:
    tracker_user.registration.type:
        class: Oro\TrackerBundle\Form\RegistrationType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: tracker_user_registration }

    event.listener:
        class: Oro\TrackerBundle\EventListener\EntityListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    project:
        class: Oro\TrackerBundle\Service\Project
        arguments: ['@service_container']

    issue:
        class: Oro\TrackerBundle\Service\Issue
        arguments: ['@service_container']

    activity:
        class: Oro\TrackerBundle\Service\Activity
        arguments: ['@service_container']

    security.access.project_voter:
        class:      Oro\TrackerBundle\Security\Authorization\Voter\ProjectVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.issue_voter:
        class:      Oro\TrackerBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.comment_voter:
        class:      Oro\TrackerBundle\Security\Authorization\Voter\CommentVoter
        public:     false
        tags:
           - { name: security.voter }