tracker_homepage:
    pattern:  /
    defaults: { _controller: OroTrackerBundle:Default:index }

tracker_issue:
    resource: "@OroTrackerBundle/Controller/IssueController.php"
    type:     annotation
    prefix:   /project/{projectCode}/issue

tracker_project:
    resource: "@OroTrackerBundle/Controller/ProjectController.php"
    type:     annotation
    prefix:   /project

tracker_activity:
    resource: "@OroTrackerBundle/Controller/ActivityController.php"
    type:     annotation
    prefix:   /activity
