services:
    collaborator.listener:
        class: Oro\Bundle\TrackerBundle\EventListener\CollaboratorListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    activity.listener:
        class: Oro\Bundle\TrackerBundle\EventListener\ActivityListener
        arguments: ['@service_container', '%mailer_user%']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    issue:
        class: Oro\Bundle\TrackerBundle\Service\Issue

    security.access.project_voter:
        class:      Oro\Bundle\TrackerBundle\Security\Authorization\Voter\ProjectVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.issue_voter:
        class:      Oro\Bundle\TrackerBundle\Security\Authorization\Voter\IssueVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.comment_voter:
        class:      Oro\Bundle\TrackerBundle\Security\Authorization\Voter\CommentVoter
        public:     false
        tags:
           - { name: security.voter }

    validator.check.member:
        class: Oro\Bundle\TrackerBundle\Validator\Constraints\CheckMemberValidator
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: validator.constraint_validator, alias: check_member }