security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OPERATOR: [ROLE_USER]
        ROLE_MANAGER: [ROLE_OPERATOR]
        ROLE_ADMINISTRATOR: [ROLE_MANAGER]


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path: tracker_homepage
            logout:
              path: fos_user_security_logout
              target: tracker_homepage
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /tracking/user, roles: ROLE_ADMINISTRATOR}
        - { path: /tracking, roles: ROLE_USER}